server:
  port: 9201 #\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: app-zuul-gateway #\u6307\u5B9A\u670D\u52A1\u540D
###\u670D\u52A1\u6CE8\u518C\u5230eureka\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://jonas:jonas@127.0.0.1:9101/eureka/,http://jonas:jonas@127.0.0.1:9102/eureka/
    ###\u56E0\u4E3A\u8BE5\u5E94\u7528\u4E3A\u670D\u52A1\u63D0\u4F9B\u8005\uFF0C\u662Feureka\u7684\u4E00\u4E2A\u5BA2\u6237\u7AEF\uFF0C\u9700\u8981\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
    register-with-eureka: true
    ###\u662F\u5426\u9700\u8981\u4ECEeureka\u4E0A\u68C0\u7D22\u670D\u52A1
    fetch-registry: true
  instance:
    prefer-ip-address: true #\u5C06\u81EA\u5DF1\u7684ip\u5730\u5740\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #\u6307\u5B9A\u5B9E\u4F8Bid
zuul:
  routes: #定义服务转发规则
    item-service: #item-service这个名字是任意写的
      path: /item-service/** #匹配item-service的请求app-item服务
      #url: http://127.0.0.1:8081 #真正的微服务地址
      serviceid: item-service-compose
    order-service: #\u540D\u5B57\u5C3D\u91CF\u548C\u4E1A\u52A1\u7CFB\u7EDF\u76F8\u5173
      path: /order-service/** #\u5339\u914Dorder-service\u7684\u8BF7\u6C42app-order\u670D\u52A1
      serviceid: order-service-compose