server:
  port: 9121
spring:
  application:
    name: order-service-compose
  datasource:
    url: jdbc:mysql://192.168.0.200:3306/springcloudplatform?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://jonas:jonas@127.0.0.1:9101/eureka/,http://jonas:jonas@127.0.0.1:9102/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
###  配置负载均衡策略
item-service-compose:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true




